from src.core.alerts import evaluate_kpi_alerts, list_alerts
from src.core.audit import list_security_audit_logs, log_security_event
from src.core.auth import (
    authenticate_user,
    create_default_admin_user,
    create_user,
    get_current_user,
    require_permission,
    require_role,
    refresh_session,
    revoke_all_sessions_for_user,
    revoke_token_session,
    verify_user_password,
)
from src.core.one_time_tokens import (
    confirm_email_verification,
    confirm_password_reset,
    request_email_verification,
    request_password_reset,
)
from src.core.cache import cache_get, cache_invalidate_prefix, cache_set, cache_stats
from src.core.database import (
    DATABASE_URL,
    AuthSession,
    ApiKey,
    DB_PATH,
    Alert,
    DatasetVersion,
    IngestionRun,
    Job,
    ModelEvaluation,
    ModelDriftRun,
    OneTimeToken,
    PreprocessingAudit,
    Product,
    ReviewProcessed,
    ReviewRaw,
    User,
    UserMFA,
    UserPermission,
    database_meta,
    ensure_database,
    get_engine,
    get_session,
    now_utc_iso,
    session_scope,
)
from src.core.drift import list_drift_runs, run_drift_detection
from src.core.evaluation import evaluate_model_quality, get_latest_evaluation
from src.core.ingestion import list_ingestion_runs, start_ingestion_scheduler, trigger_ingestion_now
from src.core.jobs import (
    get_job,
    queue_stats,
    start_job_worker,
    submit_analyze_job,
    submit_ingestion_job,
)
from src.core.logging_config import configure_logging
from src.core.metrics_export import prometheus_metrics
from src.core.metrics import metrics_snapshot
from src.core.permissions import grant_user_permission, list_user_permissions, revoke_user_permission
from src.core.rate_limit import allow_request, rate_limit_snapshot
from src.core.settings import settings
from src.core.tracing import setup_tracing

__all__ = [
    "DB_PATH",
    "DATABASE_URL",
    "AuthSession",
    "ApiKey",
    "Alert",
    "DatasetVersion",
    "IngestionRun",
    "Job",
    "ModelEvaluation",
    "ModelDriftRun",
    "OneTimeToken",
    "PreprocessingAudit",
    "Product",
    "ReviewProcessed",
    "ReviewRaw",
    "User",
    "UserMFA",
    "UserPermission",
    "authenticate_user",
    "cache_get",
    "cache_invalidate_prefix",
    "cache_set",
    "cache_stats",
    "allow_request",
    "create_default_admin_user",
    "create_user",
    "database_meta",
    "ensure_database",
    "evaluate_kpi_alerts",
    "evaluate_model_quality",
    "get_engine",
    "get_session",
    "get_current_user",
    "get_job",
    "get_latest_evaluation",
    "run_drift_detection",
    "list_drift_runs",
    "list_alerts",
    "list_ingestion_runs",
    "configure_logging",
    "metrics_snapshot",
    "prometheus_metrics",
    "now_utc_iso",
    "rate_limit_snapshot",
    "require_role",
    "require_permission",
    "grant_user_permission",
    "revoke_user_permission",
    "list_user_permissions",
    "refresh_session",
    "revoke_all_sessions_for_user",
    "revoke_token_session",
    "verify_user_password",
    "settings",
    "setup_tracing",
    "start_ingestion_scheduler",
    "start_job_worker",
    "queue_stats",
    "submit_analyze_job",
    "submit_ingestion_job",
    "trigger_ingestion_now",
    "session_scope",
    "log_security_event",
    "list_security_audit_logs",
    "request_email_verification",
    "confirm_email_verification",
    "request_password_reset",
    "confirm_password_reset",
]
